// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucgzzkowxkaidduamgvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZ3p6a293eGthaWRkdWFtZ3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTU4MjIsImV4cCI6MjA2NzMzMTgyMn0.z96sN2oxv_qQMZzet7u3gmmDaqXfcIM9qgnM1AaB9bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});